services:
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"  # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  playwright-grpc:
    build: .
    ports:
      - "50051:50051" # gRPC server
    environment:
      - PORT=50051
      - HOST=0.0.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
