name: Claude Code with S3 Backup

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-backup:
    if: |
      (github.event_name == 'issue_comment' && github.event.comment.user.login == 'takumi3488' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && github.event.comment.user.login == 'takumi3488' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && github.event.review.user.login == 'takumi3488' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.issue.user.login == 'takumi3488' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      id-token: write
      issues: write
      discussions: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Claude Code with S3 Backup
        uses: takumi3488/mygha/cca@main
        with:
          claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mc-endpoint-url: ${{ secrets.MC_ENDPOINT_URL }}
          mc-access-key: ${{ secrets.MC_ACCESS_KEY }}
          mc-secret-key: ${{ secrets.MC_SECRET_KEY }}
          s3-bucket: ${{ secrets.S3_BUCKET }}